package eu.itreegroup.spark.application.shared.search;

import java.util.HashMap;
import java.util.Map;

public class TransliterationTable {

    private static Map<Character, String> transliterationTable;
    static {
        transliterationTable = new HashMap<Character, String>();
        transliterationTable.put('Š', "S");
        transliterationTable.put('Ě', "E");
        transliterationTable.put('Í', null);
        transliterationTable.put('Á', "A");
        transliterationTable.put('É', "E");
        transliterationTable.put('Ý', "Y");
        transliterationTable.put('Ö', "O");
        transliterationTable.put('ß', "S");
        transliterationTable.put('Ü', "U");
        transliterationTable.put('Ä', "A");
        transliterationTable.put('È', "E");
        transliterationTable.put('Ç', "C");
        transliterationTable.put('Ô', "O");
        transliterationTable.put('Č', "C");
        transliterationTable.put('Ň', "N");
        transliterationTable.put('Ž', "Z");
        transliterationTable.put('Â', "A");
        transliterationTable.put('À', "A");
        transliterationTable.put('Ł', "L");
        transliterationTable.put('Ę', "E");
        transliterationTable.put('Ą', "A");
        transliterationTable.put('Ó', "O");
        transliterationTable.put('Ś', "S");
        transliterationTable.put('Ú', "U");
        transliterationTable.put('Ř', "R");
        transliterationTable.put('Ť', "T");
        transliterationTable.put('Ń', "N");
        transliterationTable.put('Î', "I");
        transliterationTable.put('Ê', "E");
        transliterationTable.put('Œ', null);
        transliterationTable.put('Ş', "S");
        transliterationTable.put('İ', "I");
        transliterationTable.put('Ș', "S");
        transliterationTable.put('Å', "A");
        transliterationTable.put('Ľ', "L");
        transliterationTable.put('Ã', "A");
        transliterationTable.put('Õ', "O");
        transliterationTable.put('Ő', "O");
        transliterationTable.put('Ț', "T");
        // transliterationTable.put(' ', null);
        transliterationTable.put('Ø', "O");
        transliterationTable.put('Ű', "U");
        transliterationTable.put('Ė', "E");
        transliterationTable.put('Ů', "U");
        transliterationTable.put('Æ', "A");
        transliterationTable.put('Ğ', "G");
        transliterationTable.put('Ż', "Z");
        transliterationTable.put('Ď', "D");
        transliterationTable.put('Ŕ', "R");
        transliterationTable.put('Б', "B");
        transliterationTable.put('О', "O");
        transliterationTable.put('Р', "R");
        transliterationTable.put('И', "I");
        transliterationTable.put('С', "S");
        transliterationTable.put('П', "P");
        transliterationTable.put('І', "I");
        transliterationTable.put('Л', "L");
        transliterationTable.put('Ь', null);
        transliterationTable.put('Ш', "SH");
        transliterationTable.put('А', "A");
        transliterationTable.put('Ï', "I");
        transliterationTable.put('Ë', "E");
        transliterationTable.put('Ε', "E");
        transliterationTable.put('Λ', "L");
        transliterationTable.put('Υ', "Y");
        transliterationTable.put('Σ', "S");
        transliterationTable.put('Ί', "I");
        transliterationTable.put('Ν', "N");
        transliterationTable.put('Α', "A");
        transliterationTable.put('Ÿ', "Y");
        transliterationTable.put('Н', "N");
        transliterationTable.put('Е', "E");
        transliterationTable.put('В', "V");
        transliterationTable.put('Д', "D");
        transliterationTable.put('Г', "G");
        transliterationTable.put('Û', "U");
        transliterationTable.put('Ć', "C");
        transliterationTable.put('Ź', "Z");
        transliterationTable.put('Ā', "A");
        transliterationTable.put('Ð', "D");
        transliterationTable.put('Ñ', "N");
        transliterationTable.put('Ņ', "N");
        transliterationTable.put('К', "K");
        transliterationTable.put('Т', "T");
        transliterationTable.put('М', "M");
        transliterationTable.put('У', "U");
        transliterationTable.put('З', "Z");
        transliterationTable.put('Й', "J");
        transliterationTable.put('Я', "JA");
        transliterationTable.put('Ы', "Y");
        transliterationTable.put('Ă', "A");
        transliterationTable.put('Ī', "I");
        transliterationTable.put('Ц', "C");
        transliterationTable.put('Ļ', "L");
        transliterationTable.put('Ē', "E");
        transliterationTable.put('Ū', "U");
        transliterationTable.put('Ķ', "K");
        transliterationTable.put('Ḷ', "L");
        transliterationTable.put('Ю', "JU");
        transliterationTable.put('Ĺ', "L");
        transliterationTable.put('‚', null);
        transliterationTable.put('Ḥ', "H");
        transliterationTable.put('Þ', null);
        transliterationTable.put('Ģ', "G");
        transliterationTable.put('Đ', "D");
        transliterationTable.put('Ò', "O");
        transliterationTable.put('Ù', "U");
        transliterationTable.put('’', "'");
        transliterationTable.put('ბ', "B");
        transliterationTable.put('ი', "I");
        transliterationTable.put('ჭ', "CH");
        transliterationTable.put('ვ', "V");
        transliterationTable.put('ნ', "N");
        transliterationTable.put('თ', "T");
        transliterationTable.put('ა', "A");
        transliterationTable.put('Ì', null);
        transliterationTable.put('Ф', "F");
        transliterationTable.put('Щ', "SCH");
        transliterationTable.put('Ё', "E");
        transliterationTable.put('ز', null);
        transliterationTable.put('ا', null);
        transliterationTable.put('خ', null);
        transliterationTable.put('و', null);
        transliterationTable.put('Ħ', null);
        transliterationTable.put('Ġ', "G");
        transliterationTable.put('Ċ', "C");
        transliterationTable.put('Η', "H");
        transliterationTable.put('Ο', "O");
        transliterationTable.put('Χ', "X");
        transliterationTable.put('Ώ', "O");
        transliterationTable.put('Ρ', "P");
        transliterationTable.put('Ι', "I");
        transliterationTable.put('Έ', "E");
        transliterationTable.put('Κ', "K");
        transliterationTable.put('Β', "B");
        transliterationTable.put('Ά', "A");
        transliterationTable.put('Թ', null);
        transliterationTable.put('Ո', null);
        transliterationTable.put('Ւ', null);
        transliterationTable.put('Մ', null);
        transliterationTable.put('Ա', null);
        transliterationTable.put('Ն', null);
        transliterationTable.put('Յ', null);
        transliterationTable.put('Չ', null);
        transliterationTable.put('Ր', null);
        transliterationTable.put('Ե', null);
        transliterationTable.put('Ց', null);
        transliterationTable.put('Վ', null);
        transliterationTable.put('Ղ', null);
        transliterationTable.put('Դ', null);
        transliterationTable.put('Ի', null);
        transliterationTable.put('Կ', null);
        transliterationTable.put('Њ', null);
        transliterationTable.put('Γ', "G");
        transliterationTable.put('Э', "E");
        transliterationTable.put('Ъ', null);
        transliterationTable.put('Є', "E");
        transliterationTable.put('Ї', "I");
        transliterationTable.put('Ј', "J");
        transliterationTable.put('Π', "P");
        transliterationTable.put('Τ', "T");
        transliterationTable.put('Μ', "M");
        transliterationTable.put('Δ', "D");
        transliterationTable.put('Ω', "O");
        transliterationTable.put('Φ', "F");
        transliterationTable.put('Θ', "F");
        transliterationTable.put('Ύ', "G");
        transliterationTable.put('Ų', "U");
        transliterationTable.put('Ξ', null);
        transliterationTable.put('Ζ', "Z");
        transliterationTable.put('Ό', "O");
        transliterationTable.put('Ή', "H");
        transliterationTable.put('Љ', null);
        transliterationTable.put('გ', "G");
        transliterationTable.put('ლ', "L");
        transliterationTable.put('ს', "S");
        transliterationTable.put('უ', "U");
        transliterationTable.put('ფ', "P");
        transliterationTable.put('Ψ', "PS");
        transliterationTable.put('Į', "I");
        transliterationTable.put('`', "'");
        transliterationTable.put('ك', null);
        transliterationTable.put('س', null);
        transliterationTable.put('ب', null);
        transliterationTable.put('Ќ', "K");
        transliterationTable.put('Ћ', null);
        transliterationTable.put('´', "'");
        transliterationTable.put('Ṥ', "S");
        transliterationTable.put('ე', "E");
        transliterationTable.put('შ', "SH");
        transliterationTable.put('ხ', "KH");
        transliterationTable.put('რ', "R");
        transliterationTable.put('Ѓ', "G");
        transliterationTable.put('ტ', "T");
        transliterationTable.put('ყ', "Q");
        transliterationTable.put('Ђ', null);
        transliterationTable.put('მ', "M");
        transliterationTable.put('დ', "D");
        transliterationTable.put('ო', "O");
        transliterationTable.put('პ', "P");
        transliterationTable.put('ღ', "GH");
        transliterationTable.put('წ', "TS");
        transliterationTable.put('Ҽ', null);
        transliterationTable.put('Ә', null);
        transliterationTable.put('კ', "K");
        transliterationTable.put('ზ', "Z");
        transliterationTable.put('ძ', "DZ");
        transliterationTable.put('ქ', "K");
        transliterationTable.put('ჩ', "CH");
        transliterationTable.put('ჯ', "J");
        transliterationTable.put('ც', "C");
        transliterationTable.put('Բ', null);
        transliterationTable.put('Շ', null);
        transliterationTable.put('Ǌ', null);
        transliterationTable.put('Џ', "C");
        transliterationTable.put('̆', "'");
        transliterationTable.put('№', "N");
        transliterationTable.put('ჟ', "ZH");
        transliterationTable.put('Ҳ', "H");
        transliterationTable.put('د', null);
        transliterationTable.put('ي', null);
        transliterationTable.put('ر', null);
        transliterationTable.put('ح', null);
        transliterationTable.put('ن', null);
        transliterationTable.put('¸', null);
        transliterationTable.put('¦', null);
        transliterationTable.put('Ǉ', null);
        transliterationTable.put('Ս', null);
        transliterationTable.put('Տ', null);
        transliterationTable.put('Զ', null);
        transliterationTable.put('Լ', null);
        transliterationTable.put('Ք', null);
        transliterationTable.put('Ձ', null);
        transliterationTable.put('Գ', null);
        transliterationTable.put('Հ', null);
        transliterationTable.put('Ֆ', null);
        transliterationTable.put('Ռ', null);
        transliterationTable.put('Ջ', null);
        transliterationTable.put('Ŷ', "Y");
        transliterationTable.put('ʹ', null);
        transliterationTable.put('Պ', null);
        transliterationTable.put('Փ', null);
        transliterationTable.put('Ŝ', "S");
        transliterationTable.put('Ճ', null);
        transliterationTable.put('Ϊ', null);
        transliterationTable.put('Խ', null);
        transliterationTable.put('–', null);
        transliterationTable.put('«', null);
        transliterationTable.put('»', null);
        transliterationTable.put('ΐ', null);
        transliterationTable.put('Ж', "ZH");
        transliterationTable.put('Х', "H");
        transliterationTable.put('Ч', "CH");
        // lower case letters 
        transliterationTable.put('ș',"s");
        transliterationTable.put('ț',"t");
        transliterationTable.put('ј',"j");
        transliterationTable.put('љ',null);
        transliterationTable.put('њ',null);
        transliterationTable.put('ћ',null);
        transliterationTable.put('ќ',"k");
        transliterationTable.put('џ',"c");
        transliterationTable.put('ё',"e");
        transliterationTable.put('ђ',null);
        transliterationTable.put('ѓ',"g");
        transliterationTable.put('є',"e");
        transliterationTable.put('і',"i");
        transliterationTable.put('ї',"i");
        transliterationTable.put('й',"j");
        transliterationTable.put('и',"i");
        transliterationTable.put('л',"l");
        transliterationTable.put('к',"k");
        transliterationTable.put('н',"n");
        transliterationTable.put('м',"m");
        transliterationTable.put('п',"p");
        transliterationTable.put('о',"o");
        transliterationTable.put('б',"b");
        transliterationTable.put('а',"a");
        transliterationTable.put('г',"g");
        transliterationTable.put('в',"v");
        transliterationTable.put('е',"e");
        transliterationTable.put('д',"d");
        transliterationTable.put('з',"z");
        transliterationTable.put('ж',"zh");
        transliterationTable.put('ъ',null);
        transliterationTable.put('ы',"y");
        transliterationTable.put('ш',"sh");
        transliterationTable.put('щ',"sch");
        transliterationTable.put('ю',"ju");
        transliterationTable.put('я',"ja");
        transliterationTable.put('ь',null);
        transliterationTable.put('э',"e");
        transliterationTable.put('т',"t");
        transliterationTable.put('у',"u");
        transliterationTable.put('р',"r");
        transliterationTable.put('с',"s");
        transliterationTable.put('ц',"c");
        transliterationTable.put('ч',"ch");
        transliterationTable.put('ф',"f");
        transliterationTable.put('х',"h");
        transliterationTable.put('ә',null);
        transliterationTable.put('í',null);
        transliterationTable.put('ì',null);
        transliterationTable.put('ï',"i");
        transliterationTable.put('î',"i");
        transliterationTable.put('é',"e");
        transliterationTable.put('è',"e");
        transliterationTable.put('ë',"e");
        transliterationTable.put('ê',"e");
        transliterationTable.put('å',"a");
        transliterationTable.put('ä',"a");
        transliterationTable.put('ç',"c");
        transliterationTable.put('æ',"a");
        transliterationTable.put('á',"a");
        transliterationTable.put('à',"a");
        transliterationTable.put('ã',"a");
        transliterationTable.put('â',"a");
        transliterationTable.put('ü',"u");
        transliterationTable.put('ý',"y");
        transliterationTable.put('þ',null);
        transliterationTable.put('ø',"o");
        transliterationTable.put('ù',"u");
        transliterationTable.put('ú',"u");
        transliterationTable.put('û',"u");
        transliterationTable.put('ô',"o");
        transliterationTable.put('õ',"o");
        transliterationTable.put('ö',"o");
        transliterationTable.put('ð',"d");
        transliterationTable.put('ñ',"n");
        transliterationTable.put('ò',"o");
        transliterationTable.put('ó',"o");
        transliterationTable.put('ҳ',"h");
        transliterationTable.put('ҽ',null);
        transliterationTable.put('ē',"e");
        transliterationTable.put('đ',"d");
        transliterationTable.put('ė',"e");
        transliterationTable.put('ֆ',null);
        transliterationTable.put('ě',"e");
        transliterationTable.put('ք',null);
        transliterationTable.put('ę',"e");
        transliterationTable.put('փ',null);
        transliterationTable.put('ğ',"g");
        transliterationTable.put('ւ',null);
        transliterationTable.put('ց',null);
        transliterationTable.put('ր',null);
        transliterationTable.put('ă',"a");
        transliterationTable.put('վ',null);
        transliterationTable.put('տ',null);
        transliterationTable.put('ռ',null);
        transliterationTable.put('ā',"a");
        transliterationTable.put('ս',null);
        transliterationTable.put('պ',null);
        transliterationTable.put('ć',"c");
        transliterationTable.put('ջ',null);
        transliterationTable.put('ą',"a");
        transliterationTable.put('ո',null);
        transliterationTable.put('չ',null);
        transliterationTable.put('ċ',"c");
        transliterationTable.put('ն',null);
        transliterationTable.put('շ',null);
        transliterationTable.put('մ',null);
        transliterationTable.put('յ',null);
        transliterationTable.put('ď',"d");
        transliterationTable.put('ղ',null);
        transliterationTable.put('ճ',null);
        transliterationTable.put('հ',null);
        transliterationTable.put('č',"c");
        transliterationTable.put('ձ',null);
        transliterationTable.put('i',"i");
        transliterationTable.put('ķ',"k");
        transliterationTable.put('ĺ',"l");
        transliterationTable.put('ļ',"l");
        transliterationTable.put('ľ',"l");
        transliterationTable.put('ġ',"g");
        transliterationTable.put('ģ',"g");
        transliterationTable.put('ħ',null);
        transliterationTable.put('ī',"i");
        transliterationTable.put('į',"i");
        transliterationTable.put('ŕ',"r");
        transliterationTable.put('œ',null);
        transliterationTable.put('ő',"o");
        transliterationTable.put('ş',"s");
        transliterationTable.put('ŝ',"s");
        transliterationTable.put('ś',"s");
        transliterationTable.put('ř',"r");
        transliterationTable.put('ň',"n");
        transliterationTable.put('ņ',"n");
        transliterationTable.put('ń',"n");
        transliterationTable.put('ł',"l");
        transliterationTable.put('թ',null);
        transliterationTable.put('ի',null);
        transliterationTable.put('ŷ',"y");
        transliterationTable.put('խ',null);
        transliterationTable.put('լ',null);
        transliterationTable.put('ű',"u");
        transliterationTable.put('կ',null);
        transliterationTable.put('ų',"u");
        transliterationTable.put('ž',"z");
        transliterationTable.put('ա',null);
        transliterationTable.put('գ',null);
        transliterationTable.put('բ',null);
        transliterationTable.put('ź',"z");
        transliterationTable.put('ե',null);
        transliterationTable.put('ÿ',"y");
        transliterationTable.put('դ',null);
        transliterationTable.put('ż',"z");
        transliterationTable.put('զ',null);
        transliterationTable.put('ť',"t");
        transliterationTable.put('š',"s");
        transliterationTable.put('ů',"u");
        transliterationTable.put('ū',"u");
        transliterationTable.put('ω',"o");
        transliterationTable.put('ψ',"ps");
        transliterationTable.put('ϊ',null);
        transliterationTable.put('υ',"y");
        transliterationTable.put('τ',"t");
        transliterationTable.put('χ',"x");
        transliterationTable.put('φ',"f");
        transliterationTable.put('ρ',"p");
        transliterationTable.put('π',"p");
        transliterationTable.put('σ',"s");
        transliterationTable.put('ξ',null);
        transliterationTable.put('ο',"o");
        transliterationTable.put('μ',"m");
        transliterationTable.put('ν',"n");
        transliterationTable.put('κ',"k");
        transliterationTable.put('λ',"l");
        transliterationTable.put('θ',"f");
        transliterationTable.put('ι',"i");
        transliterationTable.put('ζ',"z");
        transliterationTable.put('η',"h");
        transliterationTable.put('δ',"d");
        transliterationTable.put('ε',"e");
        transliterationTable.put('β',"b");
        transliterationTable.put('γ',"g");
        transliterationTable.put('α',"a");
        transliterationTable.put('ώ',"o");
        transliterationTable.put('ύ',"g");
        transliterationTable.put('ό',"o");
        transliterationTable.put('ί',"i");
        transliterationTable.put('ή',"h");
        transliterationTable.put('έ',"e");
        transliterationTable.put('ά',"a");
        transliterationTable.put('ṥ',"s");
        transliterationTable.put('ǌ',null);
        transliterationTable.put('ǉ',null);
        transliterationTable.put('ḷ',"l");
        transliterationTable.put('ḥ',"h");
    }

 /*   public static void main(String[] args) {
        for (Character key : transliterationTable.keySet()) {
            String value = transliterationTable.get(key);

            if (Character.isUpperCase(key)) {
                StringBuilder builder = new StringBuilder();
                builder.append("transliterationTable.put('");
                builder.append(Character.toLowerCase(key));
                builder.append("',");
                if (value == null) {
                    builder.append(value);
                } else {
                    builder.append("\"" + value.toLowerCase() + "\"");
                }
                builder.append(");");
                System.out.println(builder.toString());
            }

        }

    }
*/
    public static Map<Character, String> map() {
        return transliterationTable;
    }

}
